FROM mcr.microsoft.com/playwright/python:v1.41.0-jammy

WORKDIR /tests

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN playwright install chromium

CMD ["pytest", "--alluredir=./allure-results", "-v"]